_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 3
                - 53
                - 55
            "2":
                - 1
                - 3
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 32
checkpoint_dir:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_model/kinship_facenet512_pretrained/checkpoints
detector_backend:
    value: retinaface
device:
    value: cpu
distance_threshold:
    value: 0.7
early_stopping_patience:
    value: 5
exp_dir:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_model/kinship_facenet512_pretrained
exp_name:
    value: kinship_facenet512_pretrained
learning_rate:
    value: 5e-05
log_dir:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_model/kinship_facenet512_pretrained/logs
margin:
    value: 0.3
model_name:
    value: Facenet512
num_epochs:
    value: 15
num_workers:
    value: 4
output_dir:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_model
pin_memory:
    value: true
save_every:
    value: 1
scheduler_patience:
    value: 2
test_path:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_data/processed/fiw/train/splits_no_overlap_hand/test_triplets_enhanced.csv
train_path:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_data/processed/fiw/train/splits_no_overlap_hand/train_triplets_enhanced.csv
use_embedding_cache:
    value: true
val_path:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_data/processed/fiw/train/splits_no_overlap_hand/val_triplets_enhanced.csv
warmup_epochs:
    value: 1
weight_decay:
    value: 1e-06
