_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 3
                - 41
                - 53
                - 55
            "2":
                - 1
                - 3
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 64
checkpoint_dir:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_model/kinship_facenet512_pretrained/checkpoints
device:
    value: cuda
distance_threshold:
    value: 0.7
dropout_rate:
    value: 0.2
early_stopping_patience:
    value: 5
embedding_dim:
    value: 512
exp_dir:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_model/kinship_facenet512_pretrained
exp_name:
    value: kinship_facenet512_pretrained
input_shape:
    value:
        - 160
        - 160
learning_rate:
    value: 5e-05
log_dir:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_model/kinship_facenet512_pretrained/logs
margin:
    value: 0.3
model_configs:
    value:
        ArcFace:
            embedding_dim: 512
            input_shape:
                - 112
                - 112
        DeepFace:
            embedding_dim: 4096
            input_shape:
                - 152
                - 152
        Dlib:
            embedding_dim: 128
            input_shape:
                - 150
                - 150
        Facenet:
            embedding_dim: 128
            input_shape:
                - 160
                - 160
        Facenet512:
            embedding_dim: 512
            input_shape:
                - 160
                - 160
        OpenFace:
            embedding_dim: 128
            input_shape:
                - 96
                - 96
        SFace:
            embedding_dim: 512
            input_shape:
                - 112
                - 112
        VGG-Face:
            embedding_dim: 2622
            input_shape:
                - 224
                - 224
model_name:
    value: Facenet512
num_epochs:
    value: 15
num_workers:
    value: 8
output_dir:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_model
pin_memory:
    value: true
save_every:
    value: 1
scheduler_patience:
    value: 2
test_path:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_data/processed/fiw/train/splits_no_overlap_hand/test_triplets_enhanced.csv
train_path:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_data/processed/fiw/train/splits_no_overlap_hand/train_triplets_enhanced.csv
val_path:
    value: /mimer/NOBACKUP/groups/naiss2023-22-1358/samir_kinship_data/processed/fiw/train/splits_no_overlap_hand/val_triplets_enhanced.csv
warmup_epochs:
    value: 1
weight_decay:
    value: 1e-06
